const pronta=[
{name:"Apple AirPods Pro 3 USB-C",price:"R$ 1.699"},
{name:"Apple Watch SE 3 44 mm Midnight",price:"R$ 1.999"},
{name:"Apple Watch SE 3 40 mm",price:"R$ 1.799"},
{name:"Ray-Ban Meta Wayfarer Gen 2 Transitions",price:"R$ 3.999"},
{name:"Ray-Ban Meta Wayfarer Gen 2 Clear",price:"R$ 3.899"}];
const encomenda=[
{name:"Apple AirPods 4 ANC",price:"R$ 1.499",market:"R$ 1.888",save:"R$ 389",pct:"21%"},
{name:"Garmin Forerunner 165",price:"R$ 1.499",market:"R$ 1.799",save:"R$ 300",pct:"17%"}];
function Product({p,order=false}){return <article className="product"><div className="visual"><span>{p.name.split(" ")[0]}</span></div><div className="productBody"><span className={order?"badge order":"badge"}>{order?"SOB ENCOMENDA • ATÉ 10 DIAS":"PRONTA ENTREGA"}</span><h3>{p.name}</h3>{order?<><div className="compare">Referência Mercado Livre <s>{p.market}</s></div><div className="save">Você economiza {p.save} ({p.pct})</div></>:<p className="muted">Novo, lacrado e na caixa</p>}<strong className="price">{p.price}</strong><small>Frete grátis para todo o Brasil</small><button disabled>Comprar com Mercado Pago • em breve</button></div></article>}
export default function Home(){return <main><header><a className="logo" href="#">MandaDe<span>Lá</span></a><nav><a href="#pronta">Pronta entrega</a><a href="#encomenda">Sob encomenda</a><a href="#como">Como funciona</a></nav><a className="headerCta" href="#produtos">Ver produtos</a></header><section className="hero"><div><div className="eyebrow">TECNOLOGIA SEM FRONTEIRAS</div><h1>Original lá fora.<br/><span>Preço melhor aqui.</span></h1><p>Produtos 100% originais, novos, lacrados e na caixa. Escolha entre envio imediato ou encomenda com preço ainda menor.</p><div className="heroActions"><a className="primary" href="#produtos">Ver produtos</a><a className="secondary" href="#como">Como funciona</a></div></div><div className="heroCard"><div className="plane">✈</div><b>Pagamento seguro</b><span>Checkout pelo Mercado Pago</span><hr/><b>Frete grátis</b><span>Para todo o Brasil</span><hr/><b>100% original</b><span>Novo, lacrado e na caixa</span></div></section><section className="trust"><span>✓ Produtos originais</span><span>▣ Novo e lacrado</span><span>◆ Mercado Pago</span><span>🚚 Frete grátis</span></section><section id="produtos" className="content"><div id="pronta" className="sectionHead"><div><span className="kicker">ENVIO IMEDIATO</span><h2>Pronta entrega</h2><p>Já está no Brasil. Compre e receba sem esperar a encomenda.</p></div></div><div className="grid">{pronta.map((p,i)=><Product p={p} key={i}/>)}</div><div id="encomenda" className="sectionHead spaced"><div><span className="kicker gold">ECONOMIZE MAIS</span><h2>Sob encomenda</h2><p>Prazo de até 10 dias. Compare o preço e veja quanto você economiza.</p></div><div className="deadline"><b>Até 10 dias</b><span>prazo de entrega</span></div></div><div className="grid orderGrid">{encomenda.map((p,i)=><Product p={p} order key={i}/>)}</div></section><section id="como" className="how"><span className="kicker">SIMPLES E SEGURO</span><h2>Como funciona?</h2><div className="steps"><div><b>01</b><h3>Escolha</h3><p>Pronta entrega ou sob encomenda.</p></div><div><b>02</b><h3>Pague com segurança</h3><p>Pagamento processado pelo Mercado Pago.</p></div><div><b>03</b><h3>Nós enviamos</h3><p>Frete grátis e acompanhamento do pedido.</p></div><div><b>04</b><h3>Receba</h3><p>Produto original, novo e lacrado.</p></div></div></section><footer><a className="logo" href="#">MandaDe<span>Lá</span></a><p>Original lá fora. Preço melhor aqui.</p><small>Preços de referência podem variar. Comparações são informativas e devem indicar a data da consulta.</small></footer><a className="whatsapp" href="https://wa.me/" target="_blank" rel="noreferrer"><span>☏</span><b>Peça pelo WhatsApp</b></a></main>}