const pronta=[
{name:"Apple AirPods Pro 3 USB-C",price:"R$ 1.699",image:"https://www.apple.com/newsroom/images/2025/09/introducing-airpods-pro-3-the-ultimate-audio-experience/article/Apple-AirPods-Pro-3-hero-250909_big.jpg.large.jpg"},
{name:"Apple Watch SE 3 44 mm Midnight",price:"R$ 1.999",image:"https://www.apple.com/newsroom/images/2025/09/apple-watch-se-3-introduces-advanced-health-features/article/Apple-Watch-SE-3-hero-250909_big.jpg.large.jpg"},
{name:"Apple Watch SE 3 40 mm",price:"R$ 1.799",image:"https://www.apple.com/newsroom/images/2025/09/apple-watch-se-3-introduces-advanced-health-features/article/Apple-Watch-SE-3-hero-250909_big.jpg.large.jpg"},
{name:"Ray-Ban Meta Wayfarer Gen 2 Transitions",price:"R$ 3.999",image:"https://images2.ray-ban.com//cdn-record-files-pi/1d8c54ac-5cb7-4a50-bc3d-b2d800d5f86e/8a967913-09ef-4aa5-9f7d-b2d800d60003/0RW4012__601S1Z__P21__shad__qt.png"},
{name:"Ray-Ban Meta Wayfarer Gen 2 Clear",price:"R$ 3.899",image:"https://www.rkumar.in/cdn/shop/files/8056262721391_2.jpg?v=1768251894"}];
const encomenda=[
{name:"Apple AirPods 4 ANC",price:"R$ 1.499",market:"R$ 1.888",save:"R$ 389",pct:"21%",image:"https://cdsassets.apple.com/live/7WUAS350/images/tech-specs/airpods-4-anc.png"},
{name:"Garmin Forerunner 165",price:"R$ 1.499",market:"R$ 1.799",save:"R$ 300",pct:"17%",image:"https://res.garmin.com/en/products/010-02863-20/g/cf-lg-0a9ec15f-8a53-49cb-80a1-c5f04638a94c.jpg"}];
function Product({p,order=false}){return <article className="product"><div className="visual"><img src={p.image} alt={p.name}/></div><div className="productBody"><span className={order?"badge order":"badge"}>{order?"SOB ENCOMENDA • ATÉ 10 DIAS":"PRONTA ENTREGA"}</span><h3>{p.name}</h3>{order?<><div className="compare">Referência Mercado Livre <s>{p.market}</s></div><div className="save">Você economiza {p.save} ({p.pct})</div></>:<p className="muted">Novo • Lacrado • Na caixa</p>}<strong className="price">{p.price}</strong><small>Frete grátis para todo o Brasil</small><button disabled>Comprar com Mercado Pago <em>em breve</em></button></div></article>}
export default function Home(){return <main><header><a className="logo" href="#">MandaDe<span>Lá</span></a><nav><a href="#pronta">Pronta entrega</a><a href="#encomenda">Sob encomenda</a><a href="#como">Como funciona</a></nav><a className="headerCta" href="#produtos">Ver produtos</a></header><section className="hero"><div><div className="eyebrow">TECNOLOGIA SEM FRONTEIRAS</div><h1>Original lá fora.<br/><span>Preço melhor aqui.</span></h1><p>Produtos 100% originais, novos, lacrados e na caixa. Pronta entrega ou sob encomenda com preço ainda menor.</p><div className="heroActions"><a className="primary" href="#produtos">Ver produtos</a><a className="secondary" href="#encomenda">Economizar mais</a></div></div><div className="heroProduct"><img src={pronta[0].image} alt="AirPods Pro 3"/><div><span>PRONTA ENTREGA</span><b>AirPods Pro 3</b><strong>R$ 1.699</strong></div></div></section><section className="trust"><span>✓ 100% originais</span><span>▣ Novos e lacrados</span><span>◆ Pagamento Mercado Pago</span><span>🚚 Frete grátis</span></section><section id="produtos" className="content"><div id="pronta" className="sectionHead"><div><span className="kicker">ENVIO IMEDIATO</span><h2>Pronta entrega</h2><p>Produtos já no Brasil, novos, lacrados e na caixa.</p></div></div><div className="grid">{pronta.map((p,i)=><Product p={p} key={i}/>)}</div><div id="encomenda" className="sectionHead spaced"><div><span className="kicker gold">ECONOMIZE MAIS</span><h2>Sob encomenda</h2><p>Entrega em até 10 dias. Veja quanto você economiza comparando com o Mercado Livre.</p></div><div className="deadline"><b>Até 10 dias</b><span>prazo de entrega</span></div></div><div className="grid orderGrid">{encomenda.map((p,i)=><Product p={p} order key={i}/>)}</div></section><section id="como" className="how"><span className="kicker">SIMPLES E SEGURO</span><h2>Como funciona?</h2><div className="steps"><div><b>01</b><h3>Escolha</h3><p>Pronta entrega ou sob encomenda.</p></div><div><b>02</b><h3>Pague com segurança</h3><p>Pagamento processado pelo Mercado Pago.</p></div><div><b>03</b><h3>Nós enviamos</h3><p>Frete grátis e acompanhamento do pedido.</p></div><div><b>04</b><h3>Receba</h3><p>Produto original, novo e lacrado.</p></div></div></section><footer><a className="logo" href="#">MandaDe<span>Lá</span></a><p>Original lá fora. Preço melhor aqui.</p><small>Preços de referência podem variar. Comparações são informativas e devem indicar a data da consulta.</small></footer><a className="whatsapp" href="https://wa.me/" target="_blank" rel="noreferrer"><span>☏</span><b>Peça pelo WhatsApp</b></a></main>}